[package]
name = "ji-cloud-pages"
version = "0.1.0"
authors = ["dakom <david.komer@gmail.com>", "Chloe Ross <chloe@launchbadge.com>"]
edition = "2018"
publish = false

[dependencies]
actix-cors = "0.5.1"
actix-files = "0.4.0"
actix-web = "3.0.0"
anyhow = "1.0.32"
askama = "0.10.3"
core = {path = "../core"}
dotenv = "0.15"
listenfd = {version = "0.3", optional = true }
log = "0.4"
env_logger = "0.8.2"
shared = {path = "../../shared/rust", features = ["backend"]}

[features]
default = ["listenfd", "core/listenfd"]

[dependencies.serde]
version = "1.0.117"
features = ["derive"]

[dependencies.sentry]
version = "0.21.0"
default-features = false
features = ["anyhow", "backtrace", "contexts", "panic", "transport"]

# we use native-tls but this ensures we have a stable version of OpenSSL on *nix
[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
