[package]
name = "ji-cloud-pages"
version = "0.1.0"
authors = ["dakom <david.komer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.5.1"
actix-files = "0.4.0"
actix-rt = "1.0.0"
actix-service = "1.0.5"
actix-web = "3.0.0"
actix-http = "2.1.0"
anyhow = "1.0.32"
askama = "0.10.3"
config = {path = "../../config/rust"}
core = {path = "../core"}
dotenv = "0.15"
futures = "0.3.5"
jsonwebtoken = "7.1"
listenfd = {version = "0.3", optional = true }
log = "0.4"
tokio = { version = "0.2" }
serde_json = "1.0.59"
env_logger = "0.8.2"

[features]
default = ["listenfd", "core/listenfd"]

[dependencies.serde]
version = "1.0.117"
features = ["derive"]


[dependencies.sentry]
version = "0.20.1"
default-features = false
features = ["anyhow", "backtrace", "contexts", "panic", "transport"]

# we use native-tls but this ensures we have a stable version of OpenSSL on *nix
[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
