[package]
name = "app-home"
version = "0.1.0"
description = "App"
authors = ["David Komer <david.komer@gmail.com>"]
categories = ["wasm"]
readme = "README.md"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Common deps
utils = {path = "../../utils"}
components = {path = "../../components"}
shared = {path = "../../../../../shared/rust", features = ["wasm"]}
wasm-logger = { version = "0.2.0", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
console_error_panic_hook = { version = "0.1.6", optional = true }
wasm-bindgen = { version = "0.2.76", features = ["nightly"] }
js-sys = "0.3.53"
web-sys = { version = "0.3.53", features = [
    'Url',
    'Request',
    'RequestInit',
    'Response',
    'RequestMode',
    'Headers',
    'Document', 
    'DocumentFragment',
    'HtmlTemplateElement',
    'Window',
    'Storage',
    'Location',
    'Element',
    'CssStyleDeclaration',
    'DomTokenList',
    'HtmlCollection',
    'HtmlInputElement',
    'HtmlSelectElement',
    'KeyboardEvent',
    'MouseEvent',
] }
uuid = { version = "0.8.2", features = ["serde", "wasm-bindgen"] }
wasm-bindgen-futures = "0.4.26"
simple-html-template = { version = "0.2.4", features = ["wasm"] }
htmlescape = "0.3.1"
dominator = "0.5.19"
futures-signals = "0.3.22"
dominator_helpers = "0.7.2"
serde = { version = "1.0.130", features = ["derive"] }
serde-wasm-bindgen = "0.3.1"
serde_json = "1.0.67"
futures = "0.3.17"
log = "0.4.14"
cfg-if = "1.0.0"
awsm_web = { version = "0.28.1", features = ["dom", "loaders"] }
discard = "1.0.4"
gloo-timers = { version = "0.2.1", features = ["futures"] }

#SPA specific
jsonwebtoken = "7.2.0"
chrono = { version = "0.4.19", features = ["serde"] }
chrono-tz = { version = "0.5.3", features = ["serde"] }
zxcvbn = "2.1.1"

[features]
default = ["wee_alloc"]
release = ["utils/release", "components/release"]
sandbox = ["quiet", "wasm-logger", "console_error_panic_hook", "utils/sandbox"]
ts_test = []
quiet = []
local = ["quiet", "wasm-logger", "console_error_panic_hook", "utils/local"]
