[package]
name = "utils"
version = "0.1.0"
authors = ["David Komer <david.komer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = {path = "../../../../shared/rust"}
config = {path = "../../../../config/rust"}
chrono = { version = "0.4.19", features = ["wasmbind"] }
thiserror = "1.0"
futures = "0.3.14"
itertools = "0.10.0"
async-trait = "0.1.50"
serde = { version = "1.0.125", features = ["derive"] }
serde_repr = "0.1.6"
strum = "0.20.0"
strum_macros = "0.20.1"
log = "0.4.14"
serde_json = "1.0.64"
cfg-if = "1.0.0"
wasm-bindgen = "0.2.73"
js-sys = "0.3.50"
wasm-bindgen-futures = "0.4.23"
serde-wasm-bindgen = "0.1.3"
once_cell = "1.7.2"
uuid = { version = "0.8.2", features = ["serde", "wasm-bindgen"] }
url = "2.2.1"
serde_qs = "0.8.3"
dominator = "0.5.14"
futures-signals = "0.3.19"
dominator_helpers = "0.6.0"
simple-html-template = { version = "0.2.4", features = ["wasm"] }
htmlescape = "0.3.1"
web-sys = { version = "0.3.50", features = [
    'Url',
    'Request',
    'RequestInit',
    'RequestCredentials',
    'Response',
    'RequestMode',
    'Headers',
    'Window',
    'Document',
    'Element',
    'Location',
    'Storage',
    'UrlSearchParams',
    'CssStyleDeclaration',
    'DomRect',
    'HtmlDocument',
    'HtmlImageElement',
    'History',
    'CustomEvent',
] }
awsm_web = { version = "0.17.2", features = ["loaders", "serde_iso"] }
anyhow = "1.0.40"
rgb = "0.8.27"

[features]
quiet = []
local = ["quiet"]
release = []
sandbox = []
