[package]
name = "utils"
version = "0.1.0"
authors = ["David Komer <david.komer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = {path = "../../../../shared/rust", features = ["wasm"]}
chrono = { version = "0.4.19", features = ["wasmbind"] }
thiserror = "1.0.28"
futures = "0.3.17"
itertools = "0.10.1"
async-trait = "0.1.51"
serde = { version = "1.0.130", features = ["derive"] }
serde_repr = "0.1.7"
base64 = "0.13.0"
strum = "0.21.0"
strum_macros = "0.21.1"
log = "0.4.14"
serde_json = "1.0.67"
cfg-if = "1.0.0"
wasm-bindgen = "0.2.76"
js-sys = "0.3.53"
wasm-bindgen-futures = "0.4.26"
serde-wasm-bindgen = "0.3.1"
once_cell = "1.8.0"
uuid = { version = "0.8.2", features = ["serde", "wasm-bindgen"] }
url = "2.2.2"
serde_qs = "0.8.4"
dominator = "0.5.21"
futures-signals = "0.3.22"
dominator_helpers = "0.7.2"
simple-html-template = { version = "0.2.4", features = ["wasm"] }
htmlescape = "0.3.1"
gloo-timers = "0.2.1"
console_error_panic_hook = { version = "0.1.6" }
wasm-logger = { version = "0.2.0", optional = true }
web-sys = { version = "0.3.53", features = [
    'Url',
    'Request',
    'RequestInit',
    'RequestCredentials',
    'Response',
    'RequestMode',
    'Headers',
    'Window',
    'Document',
    'Element',
    'Location',
    'Storage',
    'UrlSearchParams',
    'CssStyleDeclaration',
    'DomRect',
    'HtmlDocument',
    'HtmlImageElement',
    'History',
    'CustomEvent',
    'HtmlCanvasElement',
    'CanvasRenderingContext2d',
    'ImageData',
    'Blob'
] }
awsm_web = { version = "0.28.1", features = ["loaders", "image", "serde_iso", "canvas"] }
anyhow = "1.0.43"
rgb = "0.8.27"
lazy_static = "1.4.0"

[features]
debug_log = []
quiet = []
local = ["quiet", "debug_log", "wasm-logger"]
release = []
sandbox = ["debug_log", "wasm-logger"]
