# Run like: cargo make [entry task] [app name]

# TODO - cull in Duckscript: https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md#stdcollectionsarraycontains

# Allowed app names:
# dev/scratch/001
# dev/showcase/001
# user
# admin
# jig/edit
# jig/play
# module/memory/edit
# module/memory/play
# module/poster/edit
# module/poster/play

###################
## Config        ##
###################

[config]
skip_core_tasks = true
default_to_workspace = false

[env]
DOCKER_BUILDKIT = "1"
CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true

env_files = ["../../.env"]

[tasks.local-port-main]
script_runner = "@duckscript"
script = '''
set_env APP_PORT 4104 
'''

[tasks.local-port-iframe]
script_runner = "@duckscript"
script = '''
set_env APP_PORT 4105 
'''

##########################
## ENTRY                ##
##########################

[tasks.sandbox]
script_runner = "@duckscript"
script = '''
set_env APP_NAME ${1} 
cm_run_task build-sandbox
'''

[tasks.release]
script_runner = "@duckscript"
script = '''
set_env APP_NAME ${1} 
cm_run_task build-release
'''

[tasks.local-main]
script_runner = "@duckscript"
script = '''
set_env APP_NAME ${1} 
cm_run_task build-local-main
'''

[tasks.local-iframe]
script_runner = "@duckscript"
script = '''
set_env APP_NAME ${1} 
cm_run_task build-local-iframe
'''

[tasks.local-main-nomedia]
script_runner = "@duckscript"
script = '''
set_env APP_NAME ${1} 
cm_run_task build-local-main-nomedia
'''

[tasks.local-iframe-nomedia]
script_runner = "@duckscript"
script = '''
set_env APP_NAME ${1} 
cm_run_task build-local-iframe-nomedia
'''

#######################
## COMMON            ##
#######################
[tasks.clean-templates]
script_runner = "@duckscript"
script = '''
rm -rf ../.template_output
'''

#######################
## BUILD - SANDBOX ##
#######################
[tasks.build-sandbox]
run_task = {name = [
    "clean-templates",
    "sandbox-build-templates",
    "sandbox-build-app",
]}

[tasks.sandbox-build-templates]
command = "cargo"
args = ["run", "--", "--remote-target", "sandbox"]
cwd = "../build-utils/templates-builder"


[tasks.sandbox-build-app]
script_runner = "@shell"
script = ["npm run build:sandbox"]

#######################
## BUILD - RELEASE   ##
#######################
[tasks.build-release]
run_task = {name = [
    "clean-templates",
    "release-build-templates",
    "release-build-app",
]}

[tasks.release-build-templates]
command = "cargo"
args = ["run", "--", "--remote-target", "release"]
cwd = "../build-utils/templates-builder"


[tasks.release-build-app]
script_runner = "@shell"
script = ["npm run build:release"]

###################
## local ##
###################
[tasks.build-local-main]
run_task = {name = [
    "clean-templates",
    "local-port-main",
    "local-build-templates",
    "local-prep-files",
    "local-start",
]}

[tasks.build-local-iframe]
run_task = {name = [
    "clean-templates",
    "local-port-iframe",
    "local-build-templates",
    "local-prep-files",
    "local-start",
]}

[tasks.build-local-main-nomedia]
run_task = {name = [
    "local-port-main",
    "local-prep-files",
    "local-watch-app",
]}

[tasks.bild-local-iframe-nomedia]
run_task = {name = [
    "local-port-iframe",
    "local-prep-files",
    "local-watch-app",
]}

[tasks.local-prep-files]
script_runner = "@shell"
script = ["npm run local-dev-files"]
cwd = "../build-utils"

[tasks.local-build-templates]
command = "cargo"
args = ["run", "--", "--remote-target", "local"]
cwd = "../build-utils/templates-builder"

[tasks.local-start]
run_task = { name = [
    "local-start-mediaserver",
    "local-watch-css-tailwind",
    "local-watch-css-plain",
    "local-watch-templates",
    "local-watch-app",
], fork = true, parallel = true }

[tasks.local-start-mediaserver]
script_runner = "@shell"
script = ["npm run local-media-server"]
cwd = "../build-utils"

# running watch from npm is not working for some reason
# so redefining it below

[tasks.local-watch-css-plain]
command = "watchexec"
args = ["-w", "src", "npm run bundle:prod"]
cwd = "../css/plain"

[tasks.local-watch-css-tailwind]
command = "watchexec"
args = ["-w", "src", "-w", "../../.template_output", "npm run bundle:prod"]
cwd = "../css/tailwind"

[tasks.local-watch-templates]
command = "cargo"
args = ["run", "--", "--remote-target", "local"]
cwd = "../build-utils/templates-builder"
watch = { watch = ["../templates"] }

[tasks.local-watch-app]
script_runner = "@shell"
script = ["npm run build:watch"]
