[package]
name = "app-matching-play"
version = "0.1.0"
description = "App"
authors = ["David Komer <david.komer@gmail.com>"]
categories = ["wasm"]
readme = "README.md"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.8.0"
utils = {path = "../../../../utils"}
components = {path = "../../../../components"}
shared = {path = "../../../../../../../shared/rust", features = ["wasm"]}
wasm-logger = { version = "0.2.0", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
console_error_panic_hook = { version = "0.1.6", optional = true }
wasm-bindgen = { version = "0.2.75", features = ["nightly"] }
js-sys = "0.3.52"
web-sys = { version = "0.3.52", features = [
    'Url',
    'Request',
    'RequestInit',
    'Response',
    'RequestMode',
    'Headers',
    'Document', 
    'DocumentFragment',
    'HtmlTemplateElement',
    'Window',
    'Storage',
    'Location',
    'Element',
    'CssStyleDeclaration',
    'DomTokenList',
    'HtmlCollection',
    'HtmlInputElement',
    'HtmlImageElement',
    'HtmlSelectElement',
    'KeyboardEvent',
    'MouseEvent',
    'FileList',
    'File',
    'DomRect',
    'HtmlIFrameElement'
] }
wasm-bindgen-futures = "0.4.25"
dominator = "0.5.19"
futures-signals = "0.3.22"
dominator_helpers = "0.7.2"
serde = { version = "1.0.127", features = ["derive"] }
serde-wasm-bindgen = "0.3.0"
serde_json = "1.0.66"
futures = "0.3.16"
log = "0.4.14"
cfg-if = "1.0.0"
awsm_web = { version = "0.25.0", features = ["dom", "loaders"] }
discard = "1.0.4"
uuid = { version = "0.8.2", features = ["serde", "wasm-bindgen"] }
url = "2.2.2"
gloo = "0.3.0"
gloo-timers = { version = "0.2.1", features = ["futures"] }
itertools = "0.10.1"
async-trait = "0.1.51"
unicode-segmentation = "1.8.0"
rand = "0.8.4"

[features]
default = ["wee_alloc"]
release = ["utils/release", "components/release"]
sandbox = ["quiet", "wasm-logger", "console_error_panic_hook", "utils/sandbox"]
ts_test = []
quiet = ["utils/quiet", "components/quiet"]
local = ["wasm-logger", "console_error_panic_hook", "utils/local"]
